language: node_js
node_js: stable

cache:
  directories:
    - node_modules

branches:
  only:
   - source

before_install:
   - npm install -g hexo-cli

install:
   - npm install
   - npm install --save hexo-deployer-git

script:
  - hexo cl
  - hexo g

after_script:
  - git config user.name "yuxma"
  - git config user.email "yuxma@gmail.com"
  - sed -i "s/gh_token/${test}/g" ./_config.yml
  - hexo d

    #after_script:
    #  - cd ./public
    #  - git init
    #  - git add .
    #  - git commit -m "Update docs"
    #  - git config user.name "yuxma"
    #  - git config user.email "yuxma@gmail.com"
    #  - git push --force --quiet "https://${test}@${GH_REF}" master:master

    #env:
    #  global:
    #   - GH_REF: github.com/mayux/mayux.github.io.git
